export const POST_USER_INFO='POST_USER_INFO'
export const POST_USER_INFO_SUCCESS='POST_USER_INFO_SUCCESS'
export const GET_USER_INFO='GET_USER_INFO'
export const GET_USER_INFO_SUCCESS='GET_USER_INFO_SUCCESS'
export const EMPTY='EMPTY'
export const DELETE_USER_INFO='DELETE_USER_INFO'
export const DELETE_USER_INFO_SUCCESS='DELETE_USER_INFO_SUCCESS'
export const UPDATE_USER_INFO='UPDATE_USER_INFO'


